categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.23.1 of cython.
long_description: |
  Cython is an optimising static compiler for both the Python programming
  language and the extended Cython programming language (based on Pyrex). It makes
  writing C extensions for Python as easy as Python itself.

  http://cython.org
name: package_cython_0_23_1
owner: yhoogstrate
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/crossmap_galaxy_wrapper
type: tool_dependency_definition
