categories:
- RNA
- Transcriptomics
- Sequence Analysis
description: featureCounts counts the number of reads aligned to defined masked regions in a reference genome
long_description: |
  Counts reads aligned to annotated genes in a reference genome from SAM or BAM files.
name: featurecounts
owner: yhoogstrate
homepage_url: http://bioinf.wehi.edu.au/featureCounts
remote_repository_url: https://bitbucket.org/EMCbioinf/galaxy-tool-shed-tools/raw/master/featurecounts
type: unrestricted
