categories:
- Convert Formats
- Genomic Interval Operations
description: |
  CrossMap: Convert genome coordinates or annotation files between genome assemblies
long_description: |
  CrossMap is versatile tool to convert genome coordinates or annotation files between genome
  assemblies. It supports mostly commonly used file types, including BAM, BED,BigWig, GFF,
  GTF, SAM, Wiggle, and VCF formats. For large plain text file types, such as BED, GFF, GTF
  and VCF, reading from remote servers and file compression are supported.
  
  http://crossmap.sourceforge.net/
name: crossmap
owner: yhoogstrate
homepage_url: http://crossmap.sourceforge.net/
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/crossmap_galaxy_wrapper
type: tool_dependency_definition
type: unrestricted
