categories:
- Transcriptomics
- RNA
- Statistics
description: |
  WikiPathways API tools
long_description: |
  WikiPathways is a database of biological pathways maintained by and for the scientific community. 
name: wikipathways
owner: erasmus-medical-center
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/tools/wikipathways
homepage_url: https://www.wikipathways.org/index.php/WikiPathways
type: unrestricted
