categories:
- Tool Dependency Packages
description: |
  FuMa: reporting overlap in RNA-seq detected fusion genes
long_description: |
  FuMa: reporting overlap in RNA-seq detected fusion genes.
  
  A new generation tools that allow detection of fusion genes in RNA-seq
  data are limited in either sensitivity or specificity. To allow
  further downstream analysis and to estimate performance, fusion genes
  from different tools have to be compared. Several factors complicate
  on genomic location-based matching in a transcriptome context. Here
  we present FuMa, a program that reports identical fusion genes based
  on gene-name annotations. It automatically compares and summarizes all
  combinations of two or more datasets in a single run, without
  additional programming necessary. Furthermore, FuMa uses only one
  single gene annotation, avoiding mis-matches caused by tool specific
  gene annotations. Furthermore, FuMa allows intermediate files that
  allow an in-depth analysis of corresponding tools.
name: package_fuma_2_7_1
owner: yhoogstrate
homepage_url: https://github.com/yhoogstrate/fuma
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/fuma_galaxy_wrapper
type: tool_dependency_definition
