name: pathway-viewer
owner: erasmus-medical-center
categories:
  - Sequence Analysis
description: Visualize Pathway enrichment
long_description: |
    Visualize Pathways based on differential expression data
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/tools/pathway-viewer
homepage_url: https://www.wikipathways.org/index.php/PathwayWidget
type: unrestricted
