categories:
     - Pathway Analysis
description: |
    An example of MINERVA API calls uploading overlays
long_description: |
name: minerva
owner: erasmus-medical-center
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/tools/minerva
homepage_url: https://git-r3lab.uni.lu/minerva/api-scripts/-/blob/master/Python/upload_data_overlay/3_upload_data_overlay.py
type: unrestricted
