categories:
- SAM
description: samtools - optimized for parallel mpileup generation
long_description: |
  Tool dependency definition that downloads and compiles version 0.1.19-a of samtools-parallel-mpileup.
name: package_samtools_parallel_mpileup_0_1_19_a
owner: yhoogstrate
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/samtools_parallel_mpileup_galaxy_wrapper
type: unrestricted
