categories:
- SAM
- RNA
description: "FlaiMapper: computational annotation of small ncRNA derived fragments in small RNA-seq high throughput data"
long_description: |
  FlaiMapper: computational annotation of small ncRNA derived fragments in small RNA-seq high throughput data
name: flaimapper
owner: yhoogstrate
homepage_url: https://github.com/yhoogstrate/flaimapper
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/tools/flaimapper
type: unrestricted
