categories:
- Tool Dependency Packages
description: RNA-Folding including predefined segments like K-turns and loop-E motifs
long_description: |
  Segmentation-fold is a bioinformatics application that predicts RNA 2D-structure using an extended version of the Zuker algorithm. This modification contains a new "structure elements" named Segments and SegmentLoops and is capable of folding a pre-defined substructures with multiple canonical or non-canonical pairings.
  
  This allows folding of more complex structures like K-turns and loop-E motifs, which are also part of the implemented free energy table. These thermodynamic parameters (Gibbs free energy) have been estimated in silico.

name: package_segmentation_fold_1_6_2
owner: yhoogstrate
homepage_url: https://github.com/yhoogstrate/segmentation-fold
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/segmentation_fold_galaxy_wrapper
type: tool_dependency_definition
