categories:
- Tool Dependency Packages
description: featureCounts counts the number of reads aligned to defined masked regions in a reference genome
long_description: |
  Counts reads aligned to annotated genes in a reference genome from SAM or BAM files.
name: package_featurecounts_1_4_6
owner: yhoogstrate
homepage_url: http://bioinf.wehi.edu.au/featureCounts
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/packages/package_featurecounts_1_4_6
type: tool_dependency_definition
