name: hla_dq
owner: erasmus-medical-center
categories:
    - Sequence Analysis
description: HLA-DQ typing
long_description: |
    Determine possible associated types given BLAST IMGT/HLA annotation
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/tools/hla_dq
type: unrestricted
