categories:
- Tool Dependency Packages
description: |
  FuMa: reporting overlap in RNA-seq detected fusion genes
long_description: |
  FuMa: reporting overlap in RNA-seq detected fusion genes.
  
  A new generation of tools that identify fusion genes in RNA-seq data
  is limited in either sensitivity and or specificity. To allow further
  downstream analysis and to estimate performance, predicted fusion
  genes from different tools have to be compared. However, several
  factors complicate genomic location-based matching in a transcriptome
  context. FusionMatcher (FuMa) is a program that reports identical
  fusion genes based on gene-name annotations. FuMa automatically
  compares and summarizes all combinations of two or more datasets in a
  single run, without additional programming necessary. FuMa uses only
  one single gene annotation, avoiding mismatches caused by tool
  specific gene annotations. Furthermore, FuMa accepts intermediate
  output files that allow a step wise analysis of corresponding tools.
name: package_fuma_2_11_3
owner: yhoogstrate
homepage_url: https://github.com/yhoogstrate/fuma
remote_repository_url: https://github.com/ErasmusMC-Bioinformatics/galaxytools-emc/tree/master/packages/package_fuma_2_11_3
type: tool_dependency_definition
